<?php

namespace Database\Seeders;

use App\Models\Listing;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class XpPropertyListingsSeeder extends Seeder
{
    private const USER_ID = 1;
    private const CATEGORY_ID = 222;
    private const SUB_CATEGORY_ID = 229;
    private const CHILD_CATEGORY_ID = 1158;

    public function run(): void
    {
        $sourceDirectory = database_path('seeders/assets/xp_property');
        $targetDirectory = public_path('assets/images/listing_images');

        File::ensureDirectoryExists($targetDirectory);

        foreach ($this->properties() as $property) {
            $slug = Str::slug($property['title']);
            $album = $this->copyImages($sourceDirectory, $targetDirectory, $property['image_prefix'], $slug);
            $coverImage = $album[2] ?? $album[1] ?? $album[0] ?? null;

            Listing::updateOrCreate(
                ['slug' => $slug],
                [
                    'user_id' => self::USER_ID,
                    'category_id' => self::CATEGORY_ID,
                    'sub_category_id' => self::SUB_CATEGORY_ID,
                    'child_category_id' => self::CHILD_CATEGORY_ID,
                    'listing_type' => 'normal',
                    'title' => $property['title'],
                    'description' => $property['description'],
                    'status' => 'inactive',
                    'image' => $coverImage,
                    'album' => $album,
                    'listing_data' => [
                        'price' => $property['price'],
                        'buy_now_price' => $property['price'],
                        'property_type' => 'Apartment',
                        'project' => $property['project'],
                        'tower' => $property['tower'],
                        'bedrooms' => $property['bedrooms'],
                        'unit_type' => $property['unit_type'],
                        'size_sqft' => $property['size_sqft'],
                        'view' => $property['view'],
                        'price_per_sqft' => $property['price_per_sqft'],
                        'down_payment' => $property['down_payment'],
                        'monthly_installment' => $property['monthly_installment'],
                        'payment_plan' => $property['payment_plan'],
                        'possession' => $property['possession'],
                        'source_pdf' => $property['source_pdf'],
                    ],
                    'category_features' => [
                        'bedrooms' => $property['bedrooms'],
                        'size_sqft' => $property['size_sqft'],
                        'view' => $property['view'],
                        'possession' => $property['possession'],
                    ],
                ]
            );
        }
    }

    private function copyImages(string $sourceDirectory, string $targetDirectory, string $prefix, string $slug): array
    {
        $paths = [];

        for ($page = 1; $page <= 3; $page++) {
            $source = $sourceDirectory . DIRECTORY_SEPARATOR . "{$prefix}-page-{$page}.jpg";

            if (!File::exists($source)) {
                continue;
            }

            $filename = "{$slug}-page-{$page}.jpg";
            $target = $targetDirectory . DIRECTORY_SEPARATOR . $filename;
            File::copy($source, $target);

            $paths[] = "assets/images/listing_images/{$filename}";
        }

        return $paths;
    }

    private function propertyDescription(array $property): string
    {
        return implode("\n\n", [
            "{$property['title']} is a {$property['bedrooms']}-bed apartment in {$property['project']} at HMR Waterfront, DHA Phase VIII Extension, Karachi.",
            "Unit details: {$property['unit_type']}, {$property['size_sqft']} sq. ft., {$property['view']} view, priced at PKR " . number_format($property['price']) . ".",
            "Payment plan: {$property['payment_plan']}. Possession / completion: {$property['possession']}.",
            "Note: DHA allotment, utility connection, development, floor, view, and corner premium charges may apply separately as mentioned in the source payment plan.",
        ]);
    }

    private function make(array $property): array
    {
        return $property + [
            'description' => $this->propertyDescription($property),
            'tower' => $property['project'],
        ];
    }

    private function properties(): array
    {
        return array_map(fn (array $property) => $this->make($property), [
            [
                'image_prefix' => 'xp-property-01',
                'source_pdf' => '1- 1 Bed 862 C1.pdf',
                'title' => 'Gold Crest Bay Sands Tower 2 - 1 Bed Type C1 862 sqft',
                'project' => 'Gold Crest Bay Sands Tower 2',
                'unit_type' => '1 Bed - Type C1',
                'bedrooms' => 1,
                'size_sqft' => 862,
                'view' => 'Partial Sea + Park + Emaar',
                'price_per_sqft' => 42000,
                'price' => 36204000,
                'down_payment' => 7240800,
                'monthly_installment' => 550930,
                'payment_plan' => '20% down payment, 70% over 46 monthly installments from Aug 2026, 10% on completion.',
                'possession' => 'Jun 2030',
            ],
            [
                'image_prefix' => 'xp-property-02',
                'source_pdf' => '2- 1 Bed 862 C1 Plus.pdf',
                'title' => 'Gold Crest Bay Sands Tower 2 - 1 Bed Type C1 Plus 862 sqft',
                'project' => 'Gold Crest Bay Sands Tower 2',
                'unit_type' => '1 Bed - Type C1 Plus',
                'bedrooms' => 1,
                'size_sqft' => 862,
                'view' => 'Sea & Beach',
                'price_per_sqft' => 42000,
                'price' => 36204000,
                'down_payment' => 7240800,
                'monthly_installment' => 550930,
                'payment_plan' => '20% down payment, 70% over 46 monthly installments from Aug 2026, 10% on completion.',
                'possession' => 'Jun 2030',
            ],
            [
                'image_prefix' => 'xp-property-03',
                'source_pdf' => '6- 2 Bed 1724 D1.pdf',
                'title' => 'Gold Crest Bay Sands Tower 2 - 2 Bed Type D1 1724 sqft',
                'project' => 'Gold Crest Bay Sands Tower 2',
                'unit_type' => '2 Bed - Type D1',
                'bedrooms' => 2,
                'size_sqft' => 1724,
                'view' => 'Partial Sea + Park + Emaar',
                'price_per_sqft' => 42000,
                'price' => 72408000,
                'down_payment' => 14481600,
                'monthly_installment' => 1101861,
                'payment_plan' => '20% down payment, 70% over 46 monthly installments from Aug 2026, 10% on completion.',
                'possession' => 'Jun 2030',
            ],
            [
                'image_prefix' => 'xp-property-04',
                'source_pdf' => '7- 2 Bed 1724 D1 Plus.pdf',
                'title' => 'Gold Crest Bay Sands Tower 2 - 2 Bed Type D1 Plus 1724 sqft',
                'project' => 'Gold Crest Bay Sands Tower 2',
                'unit_type' => '2 Bed - Type D1 Plus',
                'bedrooms' => 2,
                'size_sqft' => 1724,
                'view' => 'Sea + Beach + Pool + HMR',
                'price_per_sqft' => 42000,
                'price' => 72408000,
                'down_payment' => 14481600,
                'monthly_installment' => 1101861,
                'payment_plan' => '20% down payment, 70% over 46 monthly installments from Aug 2026, 10% on completion.',
                'possession' => 'Jun 2030',
            ],
            [
                'image_prefix' => 'xp-property-05',
                'source_pdf' => '11- 3 Bed 2666 A.pdf',
                'title' => 'Gold Crest Bay Sands Tower 2 - 3 Bed Type A Corner 2666 sqft',
                'project' => 'Gold Crest Bay Sands Tower 2',
                'unit_type' => '3 Bed - Type A Corner',
                'bedrooms' => 3,
                'size_sqft' => 2666,
                'view' => 'Sea + Beach + HMR + Pool',
                'price_per_sqft' => 42000,
                'price' => 111972000,
                'down_payment' => 22394400,
                'monthly_installment' => 1703922,
                'payment_plan' => '20% down payment, 70% over 46 monthly installments from Aug 2026, 10% on completion.',
                'possession' => 'Jun 2030',
            ],
            [
                'image_prefix' => 'xp-property-06',
                'source_pdf' => '12- 3 Bed 2739 A1.pdf',
                'title' => 'Gold Crest Bay Sands Tower 2 - 3 Bed Type A1 Corner 2739 sqft',
                'project' => 'Gold Crest Bay Sands Tower 2',
                'unit_type' => '3 Bed - Type A1 Corner',
                'bedrooms' => 3,
                'size_sqft' => 2739,
                'view' => 'Sea + Beach + HMR',
                'price_per_sqft' => 42000,
                'price' => 115038000,
                'down_payment' => 23007600,
                'monthly_installment' => 1750578,
                'payment_plan' => '20% down payment, 70% over 46 monthly installments from Aug 2026, 10% on completion.',
                'possession' => 'Jun 2030',
            ],
            [
                'image_prefix' => 'xp-property-07',
                'source_pdf' => '13- 3 Bed 3090 A Plus.pdf',
                'title' => 'Gold Crest Bay Sands Tower 2 - 3 Bed Type A Plus Corner 3090 sqft',
                'project' => 'Gold Crest Bay Sands Tower 2',
                'unit_type' => '3 Bed - Type A Plus Corner',
                'bedrooms' => 3,
                'size_sqft' => 3090,
                'view' => 'Sea + Beach + HMR + Pool',
                'price_per_sqft' => 42000,
                'price' => 129780000,
                'down_payment' => 25956000,
                'monthly_installment' => 1974913,
                'payment_plan' => '20% down payment, 70% over 46 monthly installments from Aug 2026, 10% on completion.',
                'possession' => 'Jun 2030',
            ],
            [
                'image_prefix' => 'xp-property-08',
                'source_pdf' => 'Metro-Type A-3 bed-2624 Sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type A 3 Bed 2624 sqft',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type A - 3 Bed',
                'bedrooms' => 3,
                'size_sqft' => 2624,
                'view' => 'Sea Facing',
                'price_per_sqft' => 44000,
                'price' => 115456000,
                'down_payment' => 11545600,
                'monthly_installment' => 1245113,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-09',
                'source_pdf' => 'Metro-Type A-3 bed-2624 Sqft Unit 4.pdf',
                'title' => 'Beach Terraces by Metro - Type A 3 Bed 2624 sqft Unit 4',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type A - 3 Bed Unit 4',
                'bedrooms' => 3,
                'size_sqft' => 2624,
                'view' => 'Sea Facing',
                'price_per_sqft' => 44000,
                'price' => 115456000,
                'down_payment' => 11545600,
                'monthly_installment' => 1245113,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-10',
                'source_pdf' => 'Metro-Type B-2 bed-2078 Sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type B 2 Bed 2078 sqft',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type B - 2 Bed',
                'bedrooms' => 2,
                'size_sqft' => 2078,
                'view' => 'Sea Facing',
                'price_per_sqft' => 44000,
                'price' => 91432000,
                'down_payment' => 9143200,
                'monthly_installment' => 986031,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-11',
                'source_pdf' => 'Metro-Type B-2 bed- 2078 Sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type B 2 Bed 2078 sqft Alternate Sheet',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type B - 2 Bed',
                'bedrooms' => 2,
                'size_sqft' => 2078,
                'view' => 'Sea Facing',
                'price_per_sqft' => 44000,
                'price' => 91432000,
                'down_payment' => 9143200,
                'monthly_installment' => 986031,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-12',
                'source_pdf' => 'Metro-Type B1-2 bed-1918 Sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type B1 2 Bed 1918 sqft',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type B1 - 2 Bed',
                'bedrooms' => 2,
                'size_sqft' => 1918,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 41000,
                'price' => 78638000,
                'down_payment' => 7863800,
                'monthly_installment' => 848057,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-13',
                'source_pdf' => 'Metro-Type B2-2 bed-1198 Sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type B2 2 Bed 1198 sqft',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type B2 - 2 Bed',
                'bedrooms' => 2,
                'size_sqft' => 1198,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 41000,
                'price' => 49118000,
                'down_payment' => 4911800,
                'monthly_installment' => 529703,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-14',
                'source_pdf' => 'Metro-Type B2-2 bed-1265 sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type B2 2 Bed 1265 sqft',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type B2 - 2 Bed',
                'bedrooms' => 2,
                'size_sqft' => 1265,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 41000,
                'price' => 51865000,
                'down_payment' => 5186500,
                'monthly_installment' => 559328,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-15',
                'source_pdf' => 'Metro-Type C-1 bed-1079 sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type C 1 Bed 1079 sqft',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type C - 1 Bed',
                'bedrooms' => 1,
                'size_sqft' => 1079,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 41000,
                'price' => 44239000,
                'down_payment' => 4423900,
                'monthly_installment' => 477087,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-16',
                'source_pdf' => 'Metro-Type C2-1 bed-935 Sqft.pdf',
                'title' => 'Beach Terraces by Metro - Type C2 1 Bed 935 sqft',
                'project' => 'Beach Terraces by Metro',
                'unit_type' => 'Type C2 - 1 Bed',
                'bedrooms' => 1,
                'size_sqft' => 935,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 41000,
                'price' => 38335000,
                'down_payment' => 3833500,
                'monthly_installment' => 413416,
                'payment_plan' => '10% booking, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% possession.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-17',
                'source_pdf' => 'athens-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Athens 1935 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Athens',
                'bedrooms' => 2,
                'size_sqft' => 1935,
                'view' => 'Sea Facing',
                'price_per_sqft' => 45000,
                'price' => 87075000,
                'down_payment' => 8707500,
                'monthly_installment' => 939000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-18',
                'source_pdf' => 'sparta-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Sparta 1698 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Sparta',
                'bedrooms' => 2,
                'size_sqft' => 1698,
                'view' => 'Partial Sea',
                'price_per_sqft' => 42000,
                'price' => 71316000,
                'down_payment' => 7131600,
                'monthly_installment' => 769000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-19',
                'source_pdf' => 'Santoroni-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Santoroni 2880 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Santoroni',
                'bedrooms' => 3,
                'size_sqft' => 2880,
                'view' => 'Sea Facing',
                'price_per_sqft' => 45000,
                'price' => 129600000,
                'down_payment' => 12960000,
                'monthly_installment' => 1397000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-20',
                'source_pdf' => 'rhodes-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Rhodes 964 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Rhodes',
                'bedrooms' => 1,
                'size_sqft' => 964,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 42000,
                'price' => 40488000,
                'down_payment' => 4048800,
                'monthly_installment' => 436000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-21',
                'source_pdf' => 'Olympia-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Olympia 1355 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Olympia',
                'bedrooms' => 1,
                'size_sqft' => 1355,
                'view' => 'Partial Sea',
                'price_per_sqft' => 42000,
                'price' => 56910000,
                'down_payment' => 5691000,
                'monthly_installment' => 614000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-22',
                'source_pdf' => 'Mykonos-A-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Mykonos A 5079 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Mykonos A',
                'bedrooms' => 4,
                'size_sqft' => 5079,
                'view' => 'Sea Facing',
                'price_per_sqft' => 50000,
                'price' => 253950000,
                'down_payment' => 25395000,
                'monthly_installment' => 2738000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-23',
                'source_pdf' => 'Mykonos-b-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Mykonos B 4705 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Mykonos B',
                'bedrooms' => 4,
                'size_sqft' => 4705,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 47000,
                'price' => 221135000,
                'down_payment' => 22113500,
                'monthly_installment' => 2385000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-24',
                'source_pdf' => 'Crete-A-Type H-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Crete A Type H 14322 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Crete A Type H',
                'bedrooms' => 5,
                'size_sqft' => 14322,
                'view' => 'Sea Facing',
                'price_per_sqft' => 50000,
                'price' => 716100000,
                'down_payment' => 71610000,
                'monthly_installment' => 7722000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-25',
                'source_pdf' => 'Crete-A-type J-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Crete A Type J 13606 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Crete A Type J',
                'bedrooms' => 5,
                'size_sqft' => 13606,
                'view' => 'Sea Facing',
                'price_per_sqft' => 50000,
                'price' => 680300000,
                'down_payment' => 68030000,
                'monthly_installment' => 7336000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-26',
                'source_pdf' => 'Crete-b-Type k-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Crete B Type K 13516 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Crete B Type K',
                'bedrooms' => 5,
                'size_sqft' => 13516,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 47000,
                'price' => 635252000,
                'down_payment' => 63525200,
                'monthly_installment' => 6850000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
            [
                'image_prefix' => 'xp-property-27',
                'source_pdf' => 'Crete-b-Type L-tilt-jun.pdf',
                'title' => 'The Tilt by SIB - Crete B Type L 12745 sqft',
                'project' => 'The Tilt by SIB',
                'unit_type' => 'Crete B Type L',
                'bedrooms' => 5,
                'size_sqft' => 12745,
                'view' => 'Partial Sea Facing',
                'price_per_sqft' => 47000,
                'price' => 599015000,
                'down_payment' => 59901500,
                'monthly_installment' => 6460000,
                'payment_plan' => '10% down payment, 5% interim in Jul 2026, 5% interim in Aug 2026, 55% over 51 monthly installments from Sep 2026 to Nov 2030, 7.5% structure completion, 7.5% finishing, 10% handover.',
                'possession' => 'Dec 2030',
            ],
        ]);
    }
}
